version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.54.0
    ports:
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # Collector HTTP (OTLP)
      - "6831:6831/udp" # Agent (optional)
      - "6832:6832/udp"
      - "5778:5778"
      - "4318:4318"
      - "4317:4317" 
      - "14250:14250"
      - "14269:14269"
      - "9411:9411"      
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
